name = "claude-svg-generator"
main = "index.html"
compatibility_date = "2023-11-28"

[site]
bucket = "."

[build]
command = ""

[env.production]
routes = [
  { pattern = "/api/*", zone_name = "$YOUR_DOMAIN" }
]

[[functions]]
pattern = "/api/claude"
function = "api/claude"